import Head from 'next/head'
import {motion} from 'framer-motion'
import { Player } from './comp/player'
import { Sidebar } from './comp/sidebar'
import { Cards } from './comp/cards'
import { Footer } from './comp/footer'
export default function Home() {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Player></Player>
      <Sidebar></Sidebar>
      <div className="main">
          <Cards></Cards>
          <Footer></Footer>
      </div>
    </>
  )
}
